version: '3'

services:

  backend:
    build: .
    environment:
      DEBUG: "shinobot:*,shinojs:*"
    volumes:
      - ./:/shinobot

  arangodb:
    image: arangodb/arangodb
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: supersecretpassword
